
// Examen Civique Trainer — study bank
// Question wording below is paraphrased for practice. It is not a reproduction of the Ministry's QCM choices.
window.CIVIQUE_META = {
  updated: "2026-09-28",
  officialBank: "https://www.immigration.interieur.gouv.fr/documentation/guides-textes-et-brochures/questions-de-connaissance-pour-lexamen-civique-nationalite-francaise.html",
  officialRules: "https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000052381641",
  officialPrep: "https://formation-civique.interieur.gouv.fr/examen-civique/informations-g%C3%A9n%C3%A9rales-sur-lexamen-civique/"
};

const K = [];
const S = [];
const k=(c,t,q,a,n="")=>K.push({id:"k"+(K.length+1),c,t,q,a,n,kind:"knowledge"});
const s=(c,q,a,choices,n="")=>S.push({id:"s"+(S.length+1),c,t:"custom",q,a,choices,n,kind:"situation"});

// PRINCIPES ET VALEURS — official-bank coverage, paraphrased
k("principes","lyrics","Après « Allons enfants de la Patrie », quelle suite appartient à la Marseillaise ?","Le jour de gloire est arrivé","Il s'agit du début de l'hymne national.");
k("principes","concept","Lors d'un recrutement, quelle question est légitime ?","Une question sur les compétences utiles au poste","L'employeur doit rester centré sur l'aptitude professionnelle et éviter les critères discriminatoires.");
k("principes","concept","Déclarer ses revenus à l'administration fiscale est…","Une obligation prévue par la loi");
k("principes","concept","À quoi servent notamment les impôts en France ?","À financer les dépenses et services publics");
k("principes","concept","Que permet la liberté d'association ?","Créer une association ou y adhérer dans le respect de la loi");
k("principes","concept","Sur les réseaux sociaux, la liberté d'expression est…","Protégée mais soumise aux limites prévues par la loi");
k("principes","person","Quel prénom renvoie directement à une figure symbolique de la République ?","Marianne");
k("principes","symbol","Quelle figure personnifie la République française ?","Marianne");
k("principes","place","Où peut-on fréquemment lire « Liberté, Égalité, Fraternité » ?","Sur les bâtiments publics, notamment les mairies");
k("principes","concept","Parmi les éléments suivants, lesquels appartiennent aux symboles républicains ?","Le drapeau tricolore et la Marseillaise");
k("principes","concept","La dégradation publique du drapeau français peut-elle être sanctionnée ?","Oui, dans les cas prévus par la loi","La liberté d'expression n'empêche pas toutes les sanctions concernant les emblèmes nationaux.");
k("principes","year","À quelle période la Sécurité sociale a-t-elle été mise en place ?","1945");
k("principes","concept","Que rappelle la fête nationale du 14 juillet ?","La Révolution française et l'unité nationale","Le 14 juillet renvoie notamment à 1789 et à la Fête de la Fédération de 1790.");
k("principes","symbol","Quel couvre-chef est traditionnellement associé à Marianne ?","Le bonnet phrygien");
k("principes","symbol","Quel symbole français apparaît souvent sur les maillots des équipes nationales ?","Le coq");
k("principes","motto","Quelle est la devise de la République ?","Liberté, Égalité, Fraternité");
k("principes","concept","La liberté d'association signifie notamment…","Pouvoir se regrouper librement pour un but licite");
k("principes","concept","Qu'est-ce qu'une liberté en droit ?","La possibilité d'agir dans les limites fixées par la loi");
k("principes","document","Sur quel document officiel voit-on couramment Marianne ?","Sur certains timbres et documents officiels");
k("principes","concept","Que signifie l'égalité républicaine ?","Les mêmes droits et la même loi pour tous, sans discrimination");
k("principes","concept","Peut-on changer de religion ou ne plus en avoir en France ?","Oui, la liberté de conscience le permet");
k("principes","concept","Un usager entrant dans une mairie peut-il porter un signe religieux ?","Oui, en principe, s'il respecte le fonctionnement du service","Les usagers ne sont pas soumis à la même neutralité que les agents publics.");
k("principes","concept","L'État peut-il financer certaines activités liées au patrimoine religieux ?","Oui, dans certains cas prévus par la loi","La laïcité ne signifie pas que toute dépense publique liée à un édifice religieux est interdite.");
k("principes","year","En quelle année a été votée la loi de séparation des Églises et de l'État ?","1905");
k("principes","concept","Quel principe central pose la loi de 1905 ?","La liberté de conscience et la séparation des cultes et de l'État");
k("principes","concept","Que garantit la laïcité ?","La liberté de conscience et la neutralité de l'État");
k("principes","date","Quelle date est la Journée de la laïcité en France ?","9 décembre");
k("principes","concept","À l'école publique, quel signe religieux un élève peut-il porter ?","Un signe discret","Les signes manifestant ostensiblement une appartenance religieuse sont interdits aux élèves des écoles, collèges et lycées publics.");
k("principes","term","Comment appelle-t-on spécifiquement la haine ou les préjugés visant les Juifs ?","L'antisémitisme");
k("principes","document","Quel texte de 1905 constitue une référence majeure de la laïcité ?","La loi de séparation des Églises et de l'État");
k("principes","institution","Quelle institution doit rester neutre vis-à-vis des religions ?","L'État et ses services publics");
k("principes","concept","La laïcité, en une phrase, c'est…","La neutralité de l'État et la liberté de conscience pour chacun");
k("principes","concept","À quoi sert la Charte de la laïcité à l'école ?","À expliquer les règles et principes de la laïcité scolaire");
k("principes","concept","Qui est tenu à la neutralité religieuse dans un service public ?","Les agents publics dans l'exercice de leurs fonctions");
k("principes","term","Comment appelle-t-on une personne qui ne croit en aucun dieu ?","Un athée");

// SYSTÈME INSTITUTIONNEL ET POLITIQUE
k("institutions","institution","Qui nomme le Premier ministre ?","Le Président de la République");
k("institutions","concept","Qui peut être candidat à l'élection présidentielle ?","Une personne remplissant les conditions légales et ayant les présentations requises");
k("institutions","concept","À qui appartient la souveraineté nationale ?","Au peuple");
k("institutions","person","Lors des élections municipales, qui les électeurs choisissent-ils directement ?","Les conseillers municipaux");
k("institutions","concept","L'inscription sur les listes électorales est…","Nécessaire pour voter, sauf cas d'inscription d'office");
k("institutions","concept","Pour voter à l'élection présidentielle, il faut notamment…","Être Français, majeur et jouir de ses droits civils et politiques");
k("institutions","concept","Pour être candidat aux municipales, il faut notamment…","Remplir les conditions d'éligibilité prévues par la loi");
k("institutions","person","Parmi les autorités locales, laquelle est issue d'une élection ?","Le maire, élu par le conseil municipal");
k("institutions","concept","Quelle est une mission du maire ?","Administrer la commune et exécuter les décisions municipales");
k("institutions","institution","Sans internet, où peut-on faire une démarche d'inscription électorale ?","À la mairie");
k("institutions","number","À partir de quel âge peut-on voter en France ?","18 ans");
k("institutions","concept","Le vote est-il obligatoire en France ?","Non, le vote est un droit et un devoir civique mais il n'est pas juridiquement obligatoire");
k("institutions","concept","Peut-on choisir de ne pas respecter une loi parce qu'on n'est pas d'accord ?","Non, la loi s'impose tant qu'elle est en vigueur");
k("institutions","concept","Comment les députés sont-ils désignés ?","Ils sont élus au suffrage universel direct");
k("institutions","institution","Qui adopte les lois ?","Le Parlement");
k("institutions","concept","Quels sont les trois pouvoirs classiquement distingués ?","Législatif, exécutif et judiciaire");
k("institutions","concept","Qu'est-ce qu'un État de droit ?","Un État où les pouvoirs publics eux-mêmes sont soumis au droit");
k("institutions","number","Quelle est la durée du mandat municipal ?","6 ans");
k("institutions","person","Qui est élu aux élections législatives ?","Les députés");
k("institutions","number","Combien de temps dure le mandat présidentiel ?","5 ans");
k("institutions","number","Combien de temps dure le mandat d'un député ?","5 ans");
k("institutions","number","Combien de temps dure le mandat d'un sénateur ?","6 ans");
k("institutions","person","Qui dirige l'action du Gouvernement ?","Le Premier ministre");
k("institutions","concept","Peut-on adhérer à un parti politique en France ?","Oui, dans le respect de la loi");
k("institutions","institution","Qui peut condamner l'auteur d'un vol ?","Une juridiction judiciaire");
k("institutions","institution","Quelle collectivité gère les collèges publics ?","Le département");
k("institutions","institution","Quelle collectivité gère les écoles maternelles et élémentaires publiques ?","La commune");
k("institutions","person","Comment un maire est-il choisi ?","Il est élu par le conseil municipal");
k("institutions","institution","Qui organise principalement les transports régionaux ?","La région");
k("institutions","concept","Comment peut-on notamment réviser la Constitution ?","Par la procédure de révision constitutionnelle prévue à l'article 89");
k("institutions","person","Qui assure l'intérim de la présidence en cas de vacance ?","Le président du Sénat");
k("institutions","institution","À quoi sert le Conseil constitutionnel ?","À contrôler notamment la conformité des lois à la Constitution");
k("institutions","concept","Quelle exigence particulière concerne une candidature présidentielle ?","Obtenir les présentations d'élus requises");
k("institutions","number","Combien de départements compte la France ?","101");
k("institutions","concept","Quels sont les grands niveaux de collectivités territoriales ?","Communes, départements et régions");
k("institutions","person","Qui représente l'État dans un département ?","Le préfet");
k("institutions","concept","Quel est un rôle majeur du Président de la République ?","Veiller au respect de la Constitution et assurer la continuité de l'État");
k("institutions","concept","Quel est le rôle principal du Premier ministre ?","Diriger l'action du Gouvernement et assurer l'exécution des lois");
k("institutions","institution","À quoi sert le Défenseur des droits ?","À protéger les droits et libertés face notamment aux administrations et aux discriminations");
k("institutions","year","En quelle année la citoyenneté européenne a-t-elle été créée par le traité de Maastricht ?","1992");
k("institutions","person","Quel compositeur est associé à l'hymne européen, l'Ode à la joie ?","Ludwig van Beethoven");
k("institutions","date","Quand célèbre-t-on la Journée de l'Europe ?","9 mai");
k("institutions","place","Où se trouve le siège de la Banque centrale européenne ?","Francfort");
k("institutions","place","Où se trouve le siège principal de la Commission européenne ?","Bruxelles");
k("institutions","person","Qui siège au Parlement européen ?","Les députés européens");
k("institutions","number","Combien d'États membres compte l'Union européenne ?","27");
k("institutions","year","En quelle année le traité de Maastricht a-t-il été signé ?","1992");
k("institutions","document","Quel traité a créé l'Union européenne sous sa forme moderne ?","Le traité de Maastricht");
k("institutions","country","Quel État a quitté l'Union européenne en 2020 ?","Le Royaume-Uni");
k("institutions","concept","Quel est l'hymne de l'Union européenne ?","L'Ode à la joie");
k("institutions","symbol","À quoi ressemble le drapeau européen ?","Douze étoiles dorées en cercle sur fond bleu");
k("institutions","concept","Qui élit les députés européens ?","Les citoyens de l'Union au suffrage universel direct");
k("institutions","place","Dans quelle ville le Parlement européen tient-il ses sessions plénières principales ?","Strasbourg");

// DROITS ET DEVOIRS
k("droits","concept","À quoi sert le droit de grève ?","À permettre aux travailleurs de cesser collectivement le travail pour défendre des revendications");
k("droits","concept","Pourquoi l'État peut-il limiter certains droits ?","Pour protéger l'ordre public, les droits d'autrui et l'intérêt général dans le cadre de la loi");
k("droits","document","Quel grand texte de 1789 proclame les droits et libertés fondamentaux ?","La Déclaration des droits de l'homme et du citoyen");
k("droits","concept","Que signifie « la liberté s'arrête là où commence celle des autres » ?","On peut agir librement tant qu'on ne porte pas atteinte aux droits d'autrui");
k("droits","concept","Que dit l'article 1er de la Constitution sur la France ?","La France est une République indivisible, laïque, démocratique et sociale");
k("droits","concept","Que protège la liberté de la presse ?","Le droit d'informer et d'être informé dans les limites de la loi");
k("droits","concept","Que permet la liberté de circulation ?","Se déplacer librement sous réserve des restrictions légales");
k("droits","concept","Être citoyen d'un État signifie notamment…","Avoir des droits civiques et des devoirs envers cet État");
k("droits","concept","Que sont les droits fondamentaux ?","Des droits essentiels protégés par la Constitution, la loi et les textes internationaux");
k("droits","concept","Quel principe protège contre l'arrestation arbitraire ?","La sûreté et les garanties de la procédure légale");
k("droits","document","Quel texte de 1789 sert de référence fondamentale aux droits des citoyens ?","La Déclaration des droits de l'homme et du citoyen");
k("droits","document","Quel texte affirme que les hommes naissent et demeurent libres et égaux en droits ?","La Déclaration des droits de l'homme et du citoyen de 1789");
k("droits","concept","Quel exemple constitue une atteinte à la dignité humaine ?","Traiter une personne de manière dégradante ou inhumaine");
k("droits","concept","La liberté d'expression permet…","D'exprimer ses opinions dans les limites prévues par la loi");
k("droits","concept","Une personne placée en garde à vue peut notamment…","Demander l'assistance d'un avocat");
k("droits","concept","Tous les citoyens français doivent-ils avoir une religion ?","Non, chacun est libre de croire ou de ne pas croire");
k("droits","number","Quel est l'âge de la majorité numérique en France pour consentir seul à certains traitements de données ?","15 ans");
k("droits","place","Où peut-on fumer légalement parmi des lieux ordinaires ?","À l'extérieur, dans un lieu où l'interdiction ne s'applique pas");
k("droits","concept","Conduire une moto nécessitant un permis sans ce permis est…","Une infraction");
k("droits","concept","Que signifie le devoir de solidarité ?","Contribuer à la vie collective et aider les personnes en difficulté selon les règles communes");
k("droits","concept","Peut-on être marié simultanément à plusieurs personnes en France ?","Non, la polygamie matrimoniale n'est pas autorisée");
k("droits","concept","Faut-il déclarer ses revenus chaque année lorsque la loi l'exige ?","Oui");
k("droits","concept","Faut-il porter secours à une personne en danger lorsque cela peut être fait sans risque disproportionné ?","Oui");
k("droits","concept","Être tiré au sort comme juré d'assises crée…","Un devoir citoyen, sauf cas de dispense prévus");
k("droits","number","À partir de quel âge peut-on acheter de l'alcool en France ?","18 ans");
k("droits","concept","Ne pas respecter le code de la route peut constituer…","Une infraction pouvant entraîner des sanctions");
k("droits","concept","Une condamnation pénale peut-elle parfois entraîner la privation de certains droits civiques ?","Oui, si le juge le prononce dans les cas prévus par la loi");
k("droits","concept","Pour obtenir une carte nationale d'identité française, il faut notamment…","Être de nationalité française et fournir les justificatifs requis");
k("droits","concept","Pour quel motif la liberté d'expression peut-elle être limitée ?","Pour prévenir notamment la diffamation, la haine ou les atteintes à l'ordre public prévues par la loi");
k("droits","concept","Que doit faire un citoyen convoqué comme juré d'assises ?","Se présenter, sauf dispense ou empêchement reconnu");
k("droits","number","À quel âge atteint-on la majorité civile ?","18 ans");
k("droits","concept","Quel est un devoir essentiel du citoyen ?","Respecter les lois et contribuer aux charges publiques selon les règles");
k("droits","term","Quelle catégorie d'infraction est la plus grave ?","Le crime");
k("droits","concept","Qu'est-ce que la citoyenneté numérique ?","Exercer ses droits et responsabilités de citoyen aussi dans l'espace numérique");
k("droits","concept","Qu'est-ce que le devoir de mémoire ?","Préserver et transmettre la mémoire des événements historiques, notamment des persécutions et conflits");
k("droits","concept","Si un juge prive une personne de ses droits civiques pendant cinq ans, que se passe-t-il pendant cette durée ?","Elle ne peut pas exercer les droits concernés par la décision, comme voter si cela est prévu");

// HISTOIRE, GÉOGRAPHIE ET CULTURE
k("histoire","document","Quel grand texte juridique a été adopté sous Napoléon Ier ?","Le Code civil");
k("histoire","person","Laquelle de ces personnes a été Président de la Ve République ?","Charles de Gaulle");
k("histoire","date","Que représente le 14 juillet en France ?","La fête nationale");
k("histoire","country","Quel pays fait partie des six États fondateurs de la construction européenne ?","La France");
k("histoire","region","Dans quelle région se trouvent plusieurs plages du Débarquement de 1944 ?","La Normandie");
k("histoire","place","Dans quelle ville les rois de France étaient-ils traditionnellement sacrés ?","Reims");
k("histoire","person","Quel roi a été guillotiné pendant la Révolution française ?","Louis XVI");
k("histoire","year","En quelle année commence la Révolution française ?","1789");
k("histoire","year","En quelle année Napoléon Ier devient-il empereur ?","1804");
k("histoire","person","Quelle figure est fortement liée à la fondation de la Ve République ?","Charles de Gaulle");
k("histoire","date","De quand date l'appel du général de Gaulle à poursuivre le combat ?","18 juin 1940");
k("histoire","concept","Qu'est-ce que la Shoah ?","L'extermination des Juifs d'Europe par l'Allemagne nazie et ses collaborateurs");
k("histoire","country","Lequel de ces territoires a été colonisé par la France ?","L'Algérie");
k("histoire","year","Depuis quelle période le Président est-il élu au suffrage universel direct sous la Ve République ?","1962");
k("histoire","year","Quel traité de 1992 fonde l'Union européenne ?","Le traité de Maastricht");
k("histoire","period","Quand a eu lieu la Seconde Guerre mondiale ?","1939-1945");
k("histoire","period","Quand a eu lieu la Première Guerre mondiale ?","1914-1918");
k("histoire","person","Sous quel Président la peine de mort a-t-elle été abolie en 1981 ?","François Mitterrand");
k("histoire","date","Que commémore le 8 mai ?","La victoire de 1945 en Europe sur l'Allemagne nazie");
k("histoire","concept","Quelle organisation économique européenne naît en 1951 ?","La Communauté européenne du charbon et de l'acier (CECA)");
k("histoire","person","Quelle femme est une grande figure de la Résistance et de la mémoire de la Shoah ?","Lucie Aubrac");
k("histoire","date","Que commémore le 11 novembre ?","L'armistice de 1918 et les morts pour la France");
k("histoire","year","En quelle année l'esclavage a-t-il été définitivement aboli dans les colonies françaises ?","1848");
k("histoire","person","Quel homme politique est associé au décret d'abolition de l'esclavage de 1848 ?","Victor Schœlcher");
k("histoire","year","À partir de quelle période l'école publique primaire devient-elle gratuite avec les lois Ferry ?","1881");
k("histoire","year","Quel droit politique majeur les femmes obtiennent-elles en 1944 ?","Le droit de vote et d'éligibilité");
k("histoire","institution","Quelle organisation internationale est créée en 1945 pour promouvoir la paix ?","L'Organisation des Nations unies (ONU)");
k("histoire","year","Quand les billets et pièces en euros entrent-ils en circulation en France ?","2002");
k("histoire","date","Quand Paris est-il libéré pendant la Seconde Guerre mondiale ?","25 août 1944");
k("histoire","place","Quel port français a joué un rôle majeur dans la traite négrière au XVIIIe siècle ?","Nantes");
k("histoire","person","Quel philosophe des Lumières a dénoncé l'esclavage et l'intolérance ?","Voltaire");
k("histoire","person","Quel peintre est français ?","Claude Monet");
k("histoire","food","Quel plat est typiquement associé à la cuisine française ?","Le pot-au-feu");
k("histoire","person","Qui était Marie Curie ?","Une scientifique double prix Nobel, pionnière de la radioactivité");
k("histoire","person","Qui a peint « La Liberté guidant le peuple » ?","Eugène Delacroix");
k("histoire","place","Dans quel musée se trouve la Joconde ?","Le musée du Louvre");
k("histoire","place","Quel château proche de Paris symbolise le règne de Louis XIV ?","Le château de Versailles");
k("histoire","place","Quel site est célèbre pour ses peintures préhistoriques ?","La grotte de Lascaux");
k("histoire","person","Qui a peint la série des Nymphéas ?","Claude Monet");
k("histoire","event","Quel événement permet de visiter exceptionnellement de nombreux monuments et bâtiments publics ?","Les Journées européennes du patrimoine");
k("histoire","date","Que symbolise le 1er mai ?","La fête du Travail");
k("histoire","person","Qui était Rouget de Lisle ?","L'auteur des paroles et de la musique de la Marseillaise");
k("histoire","event","Pour quelle occasion la tour Eiffel a-t-elle été construite ?","L'Exposition universelle de 1889");
k("histoire","mountains","Quelle chaîne marque une partie de la frontière entre la France et l'Italie ?","Les Alpes");
k("histoire","person","Qui était Molière ?","Un dramaturge et comédien");
k("histoire","person","Qui était Charles Baudelaire ?","Un poète");
k("histoire","person","Qui était George Sand ?","Une romancière");
k("histoire","person","Qui était Simone de Beauvoir ?","Une philosophe et écrivaine");
k("histoire","person","Qui était Albert Camus ?","Un écrivain et philosophe");
k("histoire","person","Qui était Marguerite Yourcenar ?","Une écrivaine et la première femme élue à l'Académie française");
k("histoire","person","Qui était Paul Cézanne ?","Un peintre");
k("histoire","person","Qui était Auguste Rodin ?","Un sculpteur");
k("histoire","person","Quel compositeur est français ?","Claude Debussy");
k("histoire","person","Qui était Auguste Renoir ?","Un peintre");
k("histoire","place","Quel grand musée se trouve à Paris ?","Le musée du Louvre");
k("histoire","place","Quel monument se trouve sur un îlot rocheux en Normandie ?","Le Mont-Saint-Michel");
k("histoire","place","Quelle grande ville française compte parmi les principales métropoles du pays ?","Lyon");
k("histoire","island","Quelle île appartient aux Antilles françaises ?","La Martinique");
k("histoire","island","Laquelle de ces îles est française ?","La Corse");
k("histoire","mountain","Quel est le plus haut sommet de France ?","Le Mont Blanc");
k("histoire","island","Quelle île française se situe dans l'océan Indien ?","La Réunion");
k("histoire","department","Quel département français partage une frontière avec le Brésil ?","La Guyane");
k("histoire","place","D'où sont lancées les fusées Ariane ?","Kourou, en Guyane");
k("histoire","sea","Quelle étendue d'eau borde l'ouest de la France métropolitaine ?","L'océan Atlantique");
k("histoire","sea","Quelle mer sépare la France de l'Angleterre ?","La Manche");
k("histoire","island","Quelle île est aussi un département français d'outre-mer ?","La Réunion");
k("histoire","concept","Que désigne la France d'outre-mer ?","Les territoires français situés hors de l'Europe");
k("histoire","number","Quelle était approximativement la population de la France au 1er janvier 2025 ?","Environ 69 millions d'habitants","L'Insee l'estimait à environ 68,9 millions après révision.");
k("histoire","place","Quel est le premier port français pour le trafic de marchandises ?","Marseille-Fos");
k("histoire","number","Combien y a-t-il de régions en France métropolitaine ?","13");
k("histoire","mountains","Quelle chaîne sépare en partie la France et l'Espagne ?","Les Pyrénées");
k("histoire","island","Quelle île française se trouve à l'est de Madagascar ?","La Réunion");
k("histoire","place","Quel est le chef-lieu de l'Auvergne-Rhône-Alpes ?","Lyon");
k("histoire","place","Quel est le chef-lieu de la Bretagne ?","Rennes");
k("histoire","place","Quel est le chef-lieu de Provence-Alpes-Côte d'Azur ?","Marseille");
k("histoire","department","Quel territoire est devenu le 101e département français en 2011 ?","Mayotte");
k("histoire","region","Quelle région est particulièrement connue pour ses grandes stations de ski alpines ?","Auvergne-Rhône-Alpes");
k("histoire","river","Quel fleuve traverse Paris ?","La Seine");

// VIVRE DANS LA SOCIÉTÉ FRANÇAISE
k("vie","institution","Où déclare-t-on la naissance d'un enfant ?","À la mairie du lieu de naissance");
k("vie","concept","Quel changement un locataire peut-il généralement faire sans autorisation du propriétaire ?","Réaliser de petits aménagements qui ne transforment pas le logement");
k("vie","concept","Quel mariage produit des effets juridiques en France ?","Le mariage civil célébré par l'officier d'état civil");
k("vie","concept","Se garer sans droit sur une place réservée aux personnes handicapées est…","Interdit et sanctionnable");
k("vie","concept","Que faire d'une machine à laver hors d'usage ?","La déposer dans une filière de collecte ou déchèterie adaptée");
k("vie","concept","Dans quelle situation faut-il déclarer une naissance à l'état civil ?","Après chaque naissance");
k("vie","concept","Quand une naissance doit-elle être déclarée ?","Dans le délai légal suivant l'accouchement");
k("vie","number","Quel numéro appelle-t-on pour la police ou la gendarmerie en urgence ?","17");
k("vie","number","Quel numéro appelle-t-on pour le SAMU ?","15");
k("vie","institution","Auprès de qui les parents inscrivent-ils d'abord un enfant à l'école publique de leur commune ?","La mairie");
k("vie","concept","Après un divorce, qui exerce en principe l'autorité parentale ?","Les deux parents, sauf décision contraire du juge");
k("vie","concept","Quelle aide peut financer tout ou partie d'un avocat pour une personne aux faibles ressources ?","L'aide juridictionnelle");
k("vie","concept","Qui peut demander le divorce ?","L'un des époux ou les deux selon la procédure");
k("vie","institution","Quel organisme rembourse les soins du régime général ?","L'Assurance maladie");
k("vie","concept","La contraception est-elle accessible en France ?","Oui, selon les règles de santé applicables");
k("vie","concept","Que signifie la confidentialité médicale ?","Les informations de santé d'un patient sont protégées et ne sont pas librement divulguées");
k("vie","concept","À quoi sert la carte Vitale ?","À faciliter la prise en charge et le remboursement des soins");
k("vie","concept","À quoi sert une complémentaire santé ?","À rembourser tout ou partie des frais restant après l'Assurance maladie");
k("vie","concept","Qu'est-ce que le tiers payant ?","Un dispositif évitant d'avancer tout ou partie des frais de santé");
k("vie","concept","L'affiliation à l'Assurance maladie permet…","La prise en charge des frais de santé selon les règles applicables");
k("vie","concept","L'interruption volontaire de grossesse est-elle légale en France ?","Oui, dans les conditions prévues par la loi");
k("vie","concept","Travailler sans être déclaré est…","Du travail dissimulé, donc illégal");
k("vie","term","Que signifie SMIC ?","Salaire minimum interprofessionnel de croissance");
k("vie","concept","Quelle démarche est utile au début d'une recherche d'emploi ?","Préparer son CV et consulter les offres, notamment via France Travail");
k("vie","number","Quelle est la durée légale hebdomadaire du travail à temps complet ?","35 heures");
k("vie","concept","Qui peut demander un congé parental d'éducation sous les conditions légales ?","Le père ou la mère salarié");
k("vie","concept","Une personne étrangère en situation régulière peut-elle créer une entreprise ?","Oui, si son titre et sa situation l'y autorisent");
k("vie","concept","Une femme peut-elle créer et diriger une entreprise ?","Oui, dans les mêmes conditions qu'un homme");
k("vie","document","Quels textes encadrent notamment la relation de travail ?","Le Code du travail, la convention collective et le contrat de travail");
k("vie","institution","Quel type de litige règle le conseil de prud'hommes ?","Les litiges individuels entre salariés et employeurs liés au contrat de travail");
k("vie","concept","Qui peut adhérer à un syndicat ?","Tout salarié ou travailleur concerné selon les règles applicables");
k("vie","concept","Peut-on licencier une salariée uniquement parce qu'elle est enceinte ?","Non, la grossesse ne peut pas justifier un licenciement");
k("vie","range","Entre quels âges l'instruction est-elle obligatoire ?","De 3 à 16 ans");
k("vie","concept","Le non-respect de l'obligation d'instruction peut-il être sanctionné ?","Oui, les parents peuvent encourir des sanctions prévues par la loi");
k("vie","concept","Qu'est-ce que l'autorité parentale ?","Un ensemble de droits et devoirs exercés dans l'intérêt de l'enfant");
k("vie","concept","Quel motif d'absence scolaire peut être légitime ?","Une maladie de l'enfant");
k("vie","number","Jusqu'à quel âge l'instruction est-elle obligatoire ?","16 ans");
k("vie","number","À quel âge commence l'instruction obligatoire ?","3 ans");
k("vie","place","Quel établissement suit normalement l'école élémentaire ?","Le collège");
k("vie","concept","Un parent d'élève peut notamment…","Participer aux élections des représentants de parents");
k("vie","concept","Que prévoit l'école pour un enfant nouvellement arrivé qui ne maîtrise pas le français ?","Un accompagnement adapté pour apprendre le français et suivre la scolarité");
k("vie","concept","Un enfant en situation de handicap a-t-il droit à la scolarisation ?","Oui, l'école doit rechercher une scolarisation adaptée à ses besoins");
k("vie","number","Quelle est la durée normale du congé de paternité et d'accueil de l'enfant pour une naissance simple ?","25 jours calendaires","Depuis 2021, le congé de paternité et d'accueil de l'enfant est de 25 jours calendaires, auxquels s'ajoutent les 3 jours de congé de naissance.");
k("vie","concept","Les châtiments corporels à l'égard des enfants sont-ils admis ?","Non, l'autorité parentale s'exerce sans violences physiques ou psychologiques");

// Additional current-official-syllabus variants for breadth
k("principes","language","Quelle est la langue de la République selon la Constitution ?","Le français");
k("principes","symbol","Quelles sont les couleurs du drapeau national ?","Bleu, blanc, rouge");
k("principes","concept","Que signifie la fraternité dans la devise ?","La solidarité et l'entraide entre les personnes");
k("principes","concept","La France est quel type de République selon l'article 1er ?","Indivisible, laïque, démocratique et sociale");
k("institutions","number","Combien de députés composent l'Assemblée nationale ?","577");
k("institutions","place","Où travaille principalement le Premier ministre ?","À l'Hôtel de Matignon");
k("institutions","concept","Le Président de la République dispose-t-il de tous les pouvoirs ?","Non, les pouvoirs sont séparés et encadrés par la Constitution");
k("institutions","concept","Quel est le pouvoir législatif ?","Le pouvoir de voter les lois");
k("institutions","concept","Pourquoi séparer les pouvoirs ?","Pour éviter la concentration du pouvoir et protéger la démocratie");
k("institutions","concept","Un ministre qui enfreint la loi peut-il être poursuivi ?","Oui, il est soumis à la loi");
k("institutions","concept","Peut-on voter à la place d'une autre personne hors procuration légale ?","Non");
k("institutions","concept","Un Président peut-il rester au pouvoir après la fin légale de son mandat sans nouvelle base constitutionnelle ?","Non");
k("institutions","concept","Quelle est la devise de l'Union européenne ?","Unie dans la diversité");
k("institutions","frequency","À quelle fréquence ont lieu les élections européennes ?","Tous les 5 ans");
k("droits","concept","Que signifie PMA ?","Procréation médicalement assistée");
k("droits","concept","La peine de mort existe-t-elle en droit français ?","Non, elle est abolie");
k("droits","concept","Que signifie le droit de manifester ?","Pouvoir exprimer collectivement des revendications dans le respect des règles applicables");
k("droits","concept","Quel texte fixe l'organisation des pouvoirs publics au plus haut niveau ?","La Constitution");
k("droits","concept","Le droit de grève est-il un droit constitutionnellement protégé ?","Oui, il s'exerce dans le cadre des lois qui le réglementent");
k("droits","concept","Une femme majeure française peut-elle voter si elle jouit de ses droits civiques ?","Oui");
k("droits","concept","Jeter un mégot dans la rue est…","Interdit et passible d'une sanction");
k("droits","concept","Que doit faire une victime de violences ?","Se mettre en sécurité et contacter les secours, la police ou une structure d'aide");
k("droits","concept","Qui assure le maintien de l'ordre public ?","Les autorités publiques, notamment la police et la gendarmerie");
k("histoire","person","Quel surnom donne-t-on à Louis XIV ?","Le Roi-Soleil");
k("histoire","concept","Quel régime est proclamé en 1792 ?","La République");
k("histoire","year","Quelle peine a été abolie en France en 1981 ?","La peine de mort");
k("histoire","place","Où a lieu le débarquement allié du 6 juin 1944 ?","En Normandie");
k("histoire","continent","Quel continent a été particulièrement concerné par la décolonisation française ?","L'Afrique");
k("histoire","country","Quel pays partage une frontière terrestre avec la France métropolitaine ?","L'Espagne");
k("histoire","place","Quelle grande ville française est un important port maritime ?","Marseille");
k("histoire","country","Quel pays est frontalier de la France métropolitaine au nord-est ?","L'Allemagne");
k("histoire","region","Quelle région française est la plus peuplée ?","Île-de-France");
k("histoire","place","Quelle cathédrale parisienne a été gravement touchée par un incendie en 2019 ?","Notre-Dame de Paris");
k("vie","concept","Qu'est-ce qu'un bail locatif ?","Un contrat entre un propriétaire et un locataire");
k("vie","concept","Quelle est une mission de France Travail ?","Accompagner les demandeurs d'emploi et les employeurs");
k("vie","concept","Le droit syndical permet notamment…","D'adhérer à un syndicat et de défendre collectivement ses intérêts");
k("vie","concept","Le droit de grève permet notamment…","De cesser collectivement le travail pour soutenir des revendications professionnelles");
k("vie","concept","Qu'est-ce que l'école maternelle ?","L'école accueillant les jeunes enfants avant l'école élémentaire");
k("vie","document","Quel diplôme les élèves passent-ils généralement à la fin du collège ?","Le diplôme national du brevet");
k("vie","concept","La cantine scolaire doit-elle exclure un enfant à cause de son origine ?","Non, l'accès au service doit respecter le principe de non-discrimination");

// PRINCIPES — situational simulations (not published official questions)
s("principes","Un agent au guichet d'une préfecture souhaite porter un signe religieux très visible pendant son service. Quelle règle s'applique ?","Il doit respecter la neutralité religieuse pendant ses fonctions",["Il doit respecter la neutralité religieuse pendant ses fonctions","Il peut afficher librement ses convictions au guichet","Seuls les signes d'une religion sont interdits","Cela dépend de l'avis de chaque usager"],"Un agent public ne doit pas manifester ses convictions religieuses dans l'exercice de ses fonctions.");
s("principes","Une usagère se présente à la mairie avec un signe religieux. Que peut exiger la mairie en principe ?","Qu'elle respecte le fonctionnement du service, sans lui imposer la neutralité des agents",["Qu'elle respecte le fonctionnement du service, sans lui imposer la neutralité des agents","Qu'elle retire automatiquement tout signe religieux","Qu'elle prouve sa nationalité française","Qu'elle signe une déclaration de neutralité"],"La neutralité incombe aux agents publics, pas de la même manière aux usagers.");
s("principes","Un collège public interdit à un élève un signe religieux manifestant ostensiblement son appartenance. Cette règle correspond-elle à la loi ?","Oui",["Oui","Non, tous les signes sont toujours autorisés","Non, l'école ne peut jamais encadrer les tenues","Oui uniquement pour les élèves majeurs"],"La loi encadre les signes ostensibles dans les écoles, collèges et lycées publics.");
s("principes","Un recruteur écarte une candidate parce qu'elle est enceinte. Comment qualifier cette décision ?","Une discrimination interdite",["Une discrimination interdite","Une préférence personnelle toujours légale","Une règle normale du recrutement","Une décision imposée par la Sécurité sociale"],"La grossesse ne peut pas servir de critère discriminatoire.");
s("principes","Une personne publie une insulte raciste visant quelqu'un en raison de son origine. Peut-elle invoquer une liberté d'expression absolue ?","Non, la liberté d'expression a des limites légales",["Non, la liberté d'expression a des limites légales","Oui, internet est sans règles","Oui, si le compte est anonyme","Oui, si elle ne connaît pas la victime"],"Les propos racistes ou incitant à la haine peuvent être sanctionnés.");
s("principes","Une mairie refuse un service à une personne uniquement à cause de sa religion. Quel principe est en cause ?","Le principe d'égalité et de non-discrimination",["Le principe d'égalité et de non-discrimination","Le droit de propriété","Le secret médical","Le droit syndical"]);
s("principes","Un professeur d'école publique cherche à convertir ses élèves à sa religion pendant le cours. Est-ce compatible avec ses obligations ?","Non, il doit respecter la neutralité",["Non, il doit respecter la neutralité","Oui, s'il prévient les parents","Oui, seulement le vendredi","Oui, si la religion est majoritaire"]);
s("principes","Un adulte décide de quitter sa religion. L'État peut-il l'en empêcher ?","Non, la liberté de conscience protège ce choix",["Non, la liberté de conscience protège ce choix","Oui, toute religion est définitive","Oui, si sa famille s'y oppose","Oui, après 30 ans"]);
s("principes","Une association culturelle respecte la loi et souhaite se créer. Quel principe la protège ?","La liberté d'association",["La liberté d'association","Le droit de grève","L'autorité parentale","Le secret professionnel"]);
s("principes","Un citoyen critique pacifiquement une décision publique. Quel droit exerce-t-il principalement ?","La liberté d'expression",["La liberté d'expression","Le droit de propriété","Le droit de succession","Le droit au logement"]);
s("principes","Un service public veut favoriser systématiquement les usagers d'une origine particulière. Est-ce compatible avec la République ?","Non, le service public doit respecter l'égalité",["Non, le service public doit respecter l'égalité","Oui, si le maire est d'accord","Oui, si cela accélère les files","Oui, pour une durée de six mois"]);
s("principes","Une école publique propose un cours scientifique obligatoire. Des parents le refusent uniquement pour un motif religieux. L'enfant peut-il simplement ne pas y assister ?","Non, les enseignements obligatoires doivent être suivis",["Non, les enseignements obligatoires doivent être suivis","Oui, tout motif religieux dispense automatiquement","Oui, sans prévenir l'école","Oui, si l'enfant a moins de 16 ans"]);
s("principes","Dans une mairie, un agent traite mieux les personnes partageant ses convictions religieuses. Quelle obligation viole-t-il ?","La neutralité et l'égalité du service public",["La neutralité et l'égalité du service public","Le droit de grève","Le droit à l'image","Le secret des correspondances"]);
s("principes","Un citoyen affirme qu'il n'a aucune religion. Est-ce compatible avec la laïcité ?","Oui",["Oui","Non","Seulement après une déclaration en mairie","Seulement s'il est né en France"]);
s("principes","Un employeur demande à un candidat quelles sont ses compétences et expériences professionnelles. Est-ce en principe pertinent ?","Oui",["Oui","Non, aucune question n'est permise","Non, seules les opinions politiques peuvent être demandées","Seulement dans le secteur public"]);
s("principes","Une personne veut adhérer à une association sportive licite. Peut-elle le faire librement selon ses statuts ?","Oui",["Oui","Non, les associations sont réservées aux Français","Seulement après autorisation du préfet","Seulement si elle vote"]);
s("principes","Un agent public refuse de servir un usager athée. Est-ce acceptable ?","Non",["Non","Oui","Seulement dans une mairie","Seulement si l'agent est croyant"]);
s("principes","Un lycéen public porte un petit pendentif religieux discret. Est-il automatiquement interdit ?","Non, un signe discret n'est pas assimilé à un signe ostensiblement religieux",["Non, un signe discret n'est pas assimilé à un signe ostensiblement religieux","Oui, tout objet religieux est interdit","Oui, uniquement au lycée","Oui, sauf le mercredi"]);
s("principes","Une personne change de religion et souhaite pratiquer dans le respect de la loi. Quel principe s'applique ?","La liberté de conscience",["La liberté de conscience","L'obligation de neutralité des citoyens","L'interdiction de changer de religion","Le droit de grève"]);
s("principes","Une mairie affiche la devise « Liberté, Égalité, Fraternité » sur sa façade. Est-ce cohérent avec les symboles républicains ?","Oui",["Oui","Non","Seulement le 14 juillet","Seulement à Paris"]);
s("principes","Quelqu'un veut imposer sa religion à un autre citoyen par la contrainte. Est-ce protégé par la liberté religieuse ?","Non",["Non","Oui","Seulement dans la famille","Seulement s'il s'agit d'un adulte"]);
s("principes","Une administration demande à ses agents de ne pas afficher de préférence religieuse dans le service. Pourquoi ?","Pour garantir la neutralité du service public",["Pour garantir la neutralité du service public","Pour interdire les religions en France","Pour supprimer la liberté de conscience","Pour réserver le service aux athées"]);
s("principes","Un candidat est refusé à un emploi uniquement en raison de son handicap, sans justification objective liée au poste. Que peut-il invoquer ?","L'interdiction des discriminations",["L'interdiction des discriminations","Le droit de veto du maire","La liberté de l'employeur d'exclure tout groupe","Le secret médical de l'entreprise"]);
s("principes","Un citoyen souhaite créer un collectif pacifique pour défendre une cause licite. Quel principe est pertinent ?","La liberté d'association",["La liberté d'association","L'obligation de voter","La présomption de culpabilité","L'interdiction de se réunir"]);

// DROITS — situational simulations
s("droits","Vous voyez une personne inconsciente et pouvez appeler les secours sans vous mettre en danger. Que devez-vous faire ?","Alerter les secours et porter assistance selon vos possibilités",["Alerter les secours et porter assistance selon vos possibilités","Partir systématiquement","Attendre un policier sans appeler","Filmer la scène et repartir"],"La non-assistance à personne en danger peut être sanctionnée.");
s("droits","Une personne en garde à vue demande un avocat. Est-ce un droit qu'elle peut exercer ?","Oui",["Oui","Non","Seulement après 48 heures","Seulement si elle est française"]);
s("droits","Un propriétaire refuse un candidat uniquement à cause de son origine. Comment qualifier cela ?","Une discrimination interdite",["Une discrimination interdite","Une règle normale de location","Une obligation fiscale","Un choix toujours protégé"]);
s("droits","Un automobiliste brûle un feu rouge. Quelle conséquence est possible ?","Une sanction pour infraction au code de la route",["Une sanction pour infraction au code de la route","Aucune conséquence juridique","La perte automatique de la nationalité","Une peine décidée par le maire sans procédure"]);
s("droits","Une personne reçoit une convocation régulière comme juré d'assises. Que doit-elle faire ?","Se présenter sauf motif de dispense reconnu",["Se présenter sauf motif de dispense reconnu","L'ignorer librement","Envoyer quelqu'un à sa place","Se présenter uniquement si elle est juriste"]);
s("droits","Une personne est agressée par son conjoint. Quelle attitude est adaptée ?","Chercher de l'aide et contacter les services compétents ou les secours",["Chercher de l'aide et contacter les services compétents ou les secours","Considérer que la violence familiale n'est jamais une affaire de droit","Attendre obligatoirement plusieurs mois","Répondre par une violence plus grave"]);
s("droits","Quelqu'un publie un appel explicite à la haine contre un groupe en raison de son origine. Peut-il être sanctionné ?","Oui",["Oui","Non, jamais sur internet","Non, si le message est public","Seulement s'il est fonctionnaire"]);
s("droits","Un conducteur reçoit l'ordre légal d'un policier de s'arrêter. Que doit-il faire ?","Respecter l'ordre",["Respecter l'ordre","Décider lui-même si la loi s'applique","Continuer sauf si le policier est connu","Demander un vote des passants"]);
s("droits","Un citoyen n'est pas d'accord avec une loi. Peut-il simplement décider qu'elle ne s'applique pas à lui ?","Non",["Non","Oui","Oui s'il l'écrit sur un réseau social","Oui s'il paie ses impôts"]);
s("droits","Une personne laisse volontairement un appareil électroménager sur le trottoir hors dispositif de collecte. Est-ce acceptable ?","Non, elle doit utiliser une filière de collecte autorisée",["Non, elle doit utiliser une filière de collecte autorisée","Oui, toujours","Oui, si l'appareil est lourd","Oui, la nuit uniquement"]);
s("droits","Un salarié participe à une grève respectant les règles applicables. Exerce-t-il un droit ?","Oui",["Oui","Non","Seulement s'il est fonctionnaire","Seulement avec l'autorisation du maire"]);
s("droits","Une personne photographie une scène d'accident au lieu d'appeler les secours alors qu'une victime est en danger et qu'elle peut aider sans risque. Quelle priorité doit-elle avoir ?","Alerter les secours et assister la victime",["Alerter les secours et assister la victime","Publier la photo","Attendre que quelqu'un d'autre agisse","Quitter les lieux"]);
s("droits","Une entreprise paie volontairement un salarié sans le déclarer. Cette pratique est…","Illégale",["Illégale","Obligatoire en période d'essai","Toujours autorisée pour moins d'un mois","Une simple préférence comptable"]);
s("droits","Un adulte achète de l'alcool pour un mineur de 15 ans dans un commerce. La vente directe au mineur est-elle permise ?","Non",["Non","Oui","Oui après 20 h","Oui avec une carte scolaire"]);
s("droits","Une personne affirme que la liberté d'expression lui permet de diffamer n'importe qui. Est-ce exact ?","Non",["Non","Oui","Oui uniquement en ligne","Oui si la personne visée est connue"]);
s("droits","Un juge prononce une peine complémentaire d'interdiction de certains droits civiques. La personne peut-elle exercer ces droits pendant la durée de l'interdiction ?","Non",["Non","Oui sans restriction","Oui si elle déménage","Oui après accord d'un employeur"]);
s("droits","Une personne veut pratiquer une religion de son choix dans le respect de la loi. Quel droit la protège ?","La liberté de conscience et de religion",["La liberté de conscience et de religion","Le droit de grève","Le droit de préemption","L'obligation de neutralité des particuliers"]);
s("droits","Une femme française majeure, inscrite et jouissant de ses droits civiques, se présente pour voter. Peut-elle voter ?","Oui",["Oui","Non","Seulement si elle est mariée","Seulement après 25 ans"]);
s("droits","Un témoin voit des violences graves. Quelle conduite est civiquement et juridiquement adaptée ?","Alerter les secours ou les forces de l'ordre et aider sans se mettre en danger",["Alerter les secours ou les forces de l'ordre et aider sans se mettre en danger","Ne jamais intervenir ni prévenir personne","Diffuser uniquement la vidéo","Attendre une autorisation administrative"]);
s("droits","Une personne commet un meurtre. De quelle catégorie d'infraction s'agit-il ?","Un crime",["Un crime","Une contravention","Un simple désaccord civil","Une formalité administrative"]);
s("droits","Une personne commet un vol simple. Il s'agit généralement de…","Un délit",["Un délit","Une loi","Une élection","Un contrat civil"]);
s("droits","Quelqu'un jette un mégot sur la voie publique. Est-ce un comportement légalement neutre ?","Non, cela peut être sanctionné",["Non, cela peut être sanctionné","Oui, toujours","Oui si le mégot est éteint","Oui seulement en ville"]);
s("droits","Un parent veut forcer son enfant à subir des violences physiques comme punition. Est-ce admis par l'autorité parentale ?","Non",["Non","Oui","Oui uniquement à la maison","Oui si l'enfant a moins de 10 ans"]);
s("droits","Une personne diffuse des données personnelles d'autrui de façon illicite. Le numérique est-il un espace sans règles ?","Non",["Non","Oui","Oui après minuit","Oui si le compte est privé"]);

// expose
window.CIVIQUE_KNOWLEDGE = K;
window.CIVIQUE_SITUATIONS = S;
